repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: autopep8-wrapper
        -   id: requirements-txt-fixer
