version: '3'
services:
    mypgdb:
        image: "postgres"
        environment:
            POSTGRES_DB: lexicount
            POSTGRES_USER: sqitch
        ports:
            - "5432:5432"
    sqitch:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/sqitch"
        depends_on:
            - mypgdb
        command: ["/sqitch/start_postgres.sh"]
